### ISSUE TITLE
Object features

### ISSUE THREAD

**Issue by SebastienLinker** [aimagelab/STAGE_action_detection#1]
The paper mentions the object features come from the Visual Genome dataset. However there are several datasets on their website. Did you get the features from a network trained on objects or relationships data?

Out of curiosity, is there any reason why you did not pick ImageNet?

**Comment by matteot11** [comment]
Hi, thanks for your interest in our work!
We used a FasterRCNN trained on Visual Genome objects. We adopted models available at the following link:
https://github.com/peteanderson80/bottom-up-attention
No particular reason for the choice, it would be interesting to see how a different object detector changes STAGE performance!
