### ISSUE TITLE
actors_labels in slowfast features

### ISSUE THREAD

**Issue by rubyrosecraft** [aimagelab/STAGE_action_detection#11]
Hi, thanks for releasing your job.
I noticed that in I3D features, the shape of 'actors_labels' is set to 81. But when it comes to slowfast features, the shape is set to 80. Could you tell me why to use different settings when using different actor features?

**Comment by matteot11** [comment]
Hi, thanks for your interest in our work.

I extracted the I3D features by myself, and I considered also the background class (with index 0) when some detections didn't overlap enough with a GT box (more details in the paper). To extract SlowFast features, I used the original code in https://github.com/facebookresearch/SlowFast, with some modifications. However, in their case, all detections were related to one of the 80 AVA classes, so without the additional background class. 
Let me know if you have any other questions!

**Comment by rubyrosecraft** [comment]
Clearly! Thanks for your promote reply.
