### ISSUE TITLE
actors feature

### ISSUE THREAD

**Issue by Chuckie-He** [aimagelab/STAGE_action_detection#2]
Thank you for providing the I3D backbone features, how could I get the R101-I3D-NL backbone features?  is it convenient to make it public? thank you very much.

**Comment by matteot11** [comment]
Hi, thanks for your question. 
We have not planned the release of R101-I3D-NL features yet. But we are still working on STAGE using more robust backbones: we will update the repo with these new backbones (and if you need, with R101-I3D-NL too) as soon as possible. In the meanwhile, if you want to extract them by yourself, you can use the inference strategy and the models available at:
https://github.com/facebookresearch/video-long-term-feature-banks
Thanks again!
Matteo
