### ISSUE TITLE
About the input person boxes

### ISSUE THREAD

**Issue by Qinying-Liu** [aimagelab/STAGE_action_detection#3]
Thanks for sharing your code of STAGE.

In STAGE, the Faster R-CNN is used as the person detector.   I wonder in the training phase,  whether STAGE takes as input the detected person boxes or the ground truth boxes ? If it is the former，would you provide the code with more details of the label assignment to the boxes? Such as the threshold for assigning postive labels. Thanks

**Comment by matteot11** [comment]
Hi, thanks for your interest in our work!
Yes, we use Faster R-CNN as our person detector. During STAGE training we used both ground truth and predicted actor boxes. More details about the prediction process can be found in Sec. 4 (under 'Backbones setup' subsection) of the paper (https://arxiv.org/pdf/1912.04316.pdf): 
-For I3D we used GT boxes and predicted boxes with any detection score, assigning labels of a GT box to a predicted box if their IoU was 0.5 or more. We used predicted boxes with score>=0.7 for inference;
-For R101-I3D-NL, following authors implementation (https://github.com/facebookresearch/video-long-term-feature-banks), we used GT boxes and predicted boxes with detection score>=0.9, assigning labels of a GT box to a predicted box if their IoU was 0.9 or more. We used predicted boxes with score>=0.85 for inference (these predictions are also available at this link
https://github.com/facebookresearch/video-long-term-feature-banks/blob/master/GETTING_STARTED.md
in the 'Dataset specific details' Section).
Hoping to help you,
Matteo
