### ISSUE TITLE
actors_feature using slowfast backbone

### ISSUE THREAD

**Issue by Chuckie-He** [aimagelab/STAGE_action_detection#6]
Congratulations!
I have read your latest article, map reached 29.8, could you publish the actors features of AVA using slowfast backbone?
Thank you very much.

**Comment by matteot11** [comment]
Hi!
Thanks for your interest in our work. I have released SlowFast features, but unfortunately they are in a different format compared to I3D ones, so you should modify the dataloader code accordingly.
Sorry for the delay.

Matteo

**Comment by Chuckie-He** [comment]
Thank you, but in the ablation experiment, what you use seems to be the features of ava2.1. Is it convenient to share?

**Comment by matteot11** [comment]
Now you can find ava2.1 features, too. Hope it helps.

Matteo

**Comment by Chuckie-He** [comment]
ok, I think it's very helpful, thank you！

**Comment by Chuckie-He** [comment]
sorry, I have downloaded the files you shared, but it has errors. (ava2.1_train and ava2.1_val). I can't open them and their size are very small(69m and 256k), cuold you help?

**Comment by matteot11** [comment]
Sorry, I didn't notice an error while uploading features. Try again now and let me know :)

Matteo

**Comment by Chuckie-He** [comment]
Now it's ok, thank you for your help.
