### ISSUE TITLE
How does the clip number correspond to the clip ID

### ISSUE THREAD

**Issue by Chuckie-He** [aimagelab/STAGE_action_detection#8]
Hi, in the latest feature file(using slowfast backbone), how does the clip number correspond to the clip ID? for example, 0 is -5KQ66BBWC4.

**Comment by matteot11** [comment]
Hi! Features are extracted using the official SlowFast GitHub code and models.
You can find the id-video pairs [here](https://github.com/facebookresearch/video-long-term-feature-banks/blob/master/DATASET.md#ava). 
Under 'AVA' section, click on links to frame lists (in point 5, train or val). 
Hope it helps!
