### ISSUE TITLE
Problem when download ava_fastercnn_object_train.hdf5

### ISSUE THREAD

**Issue by rubyrosecraft** [aimagelab/STAGE_action_detection#9]
Hi, I'm trying to follow your repo. When I want to download ava_fastercnn_object_train.hdf5, I meet with a problem as follows. Can you give me help? Thanks in advance.

`Sorry, you can 't view or download this file right now.    Recently view or download this file too many users.  Please try to access this file later.  If the file you try to access is particularly large or shared by many people, it may take up to 24 hours to view or download it.  If you are still unable to access files 24 hours later, please contact your domain administrator.`

**Comment by yaru-zhang** [comment]
Hi, I'm trying to follow your repo. When I want to download ava_fastercnn_object_train.hdf5, I meet with a problem as follows. Can you give me help? Thanks in advance.

`Sorry, you can 't view or download this file right now.    Recently view or download this file too many users.  Please try to access this file later.  If the file you try to access is particularly large or shared by many people, it may take up to 24 hours to view or download it.  If you are still unable to access files 24 hours later, please contact your domain administrator.`

**Comment by yaru-zhang** [comment]
Can you share the weights [Faster-RCNN_objects_train]? My email is 340565953@qq.com

**Comment by matteot11** [comment]
Hi, I updated the file link. Please check if it works now.
You could also try to download it in Private mode.

**Comment by yaru-zhang** [comment]
> Hi, I updated the file link. Please check if it works now.
> You could also try to download it in Private mode.

@matteot11 Thanks for the prompt reply. But it still does not work for me.
Could you share the feature using other web disks (like Baidu Disk)? 

Thanks in advance.

**Comment by rubyrosecraft** [comment]
Thanks! I have accessed the file after the 24-hour limitation.
